config/routes.rb
Rails.application.routes.draw do
   resources :riders
   resources :teams

  root 'welcome#index'

end

app/models/rider.rb
class Rider < ActiveRecord::Base
    belongs_to :team, dependent: :destroy
   mount_uploader :photo, PhotoUploader
end
# It returns the articles whose titles contain one or more words that form the query
  

def self.search(search)
  if search
    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
    has_many :riders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/riders_controller.rb
class RidersController < ApplicationController
    def index
        @riders = Rider.all
         if params[:search]
           @riders = Rider.search(params[:search])
         end
    end
  
  def show
    @rider = Rider.find(params[:id])
  end
    
    def new
        @rider = Rider.new
    end
    
    def edit
        @rider = Rider.find(params[:id])
    end
      
    def create
        @rider = Rider.new(rider_params)
        if @rider.save
        redirect_to @rider
        
        end
    end
   
    def update
        @rider = Rider.find(params[:id])
        if @rider.update(rider_params)
        redirect_to @rider
        else
        render 'edit'
        end
    end
    def destroy
     @rider = Rider.find(params[:id])
     @rider.destroy
     redirect_to riders_path
    end

 private
  def rider_params
    params.require(:rider).permit(:name, :age, :druzyna, :photo)
  end



end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
     def index
    @teams = Team.all
     end
  
  def show
    @team = Team.find(params[:id])
  end
    
    def new
        @team = Team.new
    end
    
    def edit
        @team = Team.find(params[:id])
    end
      
    def create
        @team = Team.new(team_params)
        if @team.save
        redirect_to @team
        else
        render 'new'
        end
    end
   
    def update
    @team = Team.find(params[:id])
        if @team.update(team_params)
        redirect_to @team
        else
        render 'edit'
        end
    end
    
    def destroy
        @team = Team.find(params[:id])
        @team.destroy
        redirect_to teams_path
    end

 private
  def team_params
    params.require(:team).permit(:teamname, :year, :trener)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/riders_helper.rb
module RidersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  
    Made by <a href="http://www.michaelhartl.com">Marcin B</a>
  </small>
  <nav>
    <ul>
        <li><a href="http://www.sportowefakty.pl/">Najlepsza liga na świecie</a></li>
      <li><%= link_to "O stronie",   '#' %></li>
      <li><%= link_to "Kontakt", '#' %></li>
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
   
    <nav>
      <ul class="nav navbar-nav navbar-left">
        
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Zawodnicy",   riders_path %></li>
        <li><%= link_to "Drużyny",   teams_path %></li>
        <ul class="nav navbar-nav navbar-left">  
          <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
           
            <%= form_tag(riders_path, :method => "get", class: "navbar-form", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Szukaj" %>
          </div>
          <button type="submit" class="btn btn-default">Szukaj</button>
          </form>
      <% end %>
        </li>
      </ul>
        
        
        
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Liga żużlowa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <body>
        <%= render 'layouts/header' %>
        
<div class="kontener">
      <div class="container">
          
          <div class="jumbotron">

        <%= yield %>
        
        
<p></p>
</div>
        </div>
</div>
      <%= render 'layouts/footer' %>

</body>
</html>

app/views/riders/edit.html.erb
<h1>Edycja Zawodnika</h1>
 <%= form_for :rider, url: rider_path(@rider), method: :patch do |f| %>
   
   <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  
   <p>
    <%= f.label :age %><br>
    <%= f.text_area :age %>
  </p>
  <p>
    <%= f.label :druzyna %><br>
    <%= f.text_field :druzyna %>
  </p>
  <p>
      <%= f.label :photo %><br>
      <%= f.file_field :photo %>
  </p>

   <p>
    <%= f.submit %>
  </p>
   <% end %>
 <%= link_to 'Back', riders_path %>

app/views/riders/index.html.erb
<h1>Zawodnicy</h1>

<%= link_to 'Nowy', new_rider_path %>
<table>
  <tr>
    <th>Imię</th>
    <th colspan="2"></th>
  </tr>
   <% @riders.each do |rider| %>
    <tr>
      <td><%= rider.name %></td>
      <td><%= link_to 'Pokaż', rider_path(rider) %></td>
      <td><%= link_to 'Edycja', edit_rider_path(rider) %></td>
      <td><%= link_to 'Usuń', rider_path(rider),
              method: :delete,
              data: { confirm: 'Czy jestes pewien?' } %></td>
      </tr>
  <% end %>
</table>

app/views/riders/new.html.erb
<h1>Nowy Zawodnik</h1>
 
 <%= form_for :rider, url: riders_path do |f| %>
  <p>
    <%= f.label 'Imię' %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label 'Wiek' %><br>
    <%= f.text_field :age %>
  </p>
  <p>
    <%= f.label 'Drużyna' %><br>
    <%= f.text_field :druzyna %>
  </p>
  <p>
      <%= f.label 'Zdjęcie' %><br>
      <%= f.file_field :photo %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Wróc', riders_path %>

app/views/riders/show.html.erb
<p>
    <%= image_tag @rider.photo, class: "photo" %>
</p>


<h2>Imię i nazwisko:</h2>
<h1><%= @rider.name %></h1>
<h3>Wiek: <%= @rider.age %> lata</h3>
<h3>Drużyna: <%= @rider.druzyna %></h3>
  



<%= link_to 'Back', riders_path %>

app/views/welcome/index.html.erb
<h1>Liga żużlowa</h1>

<p>Strona o Polskiej Lidze Żużlowej</p>